apache: support changing ports
Currently, Apache listens on port 80. If HTTPS is enabled, it listens on
both 80 and 443. This is inflexible, especially if one wants to put the
snap behind a proxy of some kind.

Support changing HTTP and HTTPS ports via the `configure` hook.
Expose these configurations via the `ports.http` and `ports.https`
options, respectively.

Fix #134.

Signed-off-by: Kyle Fazzari <kyle@canonical.com>

diff --git a/src/apache/utilities/apache-utilities b/src/apache/utilities/apache-utilities
--- a/src/apache/utilities/apache-utilities
+++ b/src/apache/utilities/apache-utilities
@@ -1,24 +1,83 @@
 #!/bin/sh
 
+APACHE_HTTP_PORT_FILE="$SNAP_DATA/apache/data/http_port"
+APACHE_HTTPS_PORT_FILE="$SNAP_DATA/apache/data/https_port"
 export APACHE_PIDFILE="/tmp/pids/httpd.pid"
 
+mkdir -p -m 750 "$(dirname $APACHE_HTTP_PORT_FILE)"
+mkdir -p -m 750 "$(dirname $APACHE_HTTPS_PORT_FILE)"
 mkdir -p -m 750 "$(dirname $APACHE_PIDFILE)"
 
 restart_apache_if_running()
 {
-	if [ -f "$APACHE_PIDFILE" ]; then
+	if apache_is_running; then
 		# Restart apache by stopping it and letting systemd start it again.
-		apache_pid=$(cat "$APACHE_PIDFILE")
+		pid="$(apache_pid)"
 		echo -n "Restarting apache... "
 		output=$(httpd-wrapper -k stop 2>&1)
 		if [ $? -eq 0 ]; then
-			while kill -0 $apache_pid 2>/dev/null; do
+			while kill -0 $pid 2>/dev/null; do
 				sleep 1
 			done
 			echo "done"
 		else
 			echo "error"
 			echo "$output"
+			return 1
 		fi
 	fi
+}
+
+apache_is_running()
+{
+	[ -f "$APACHE_PIDFILE" ]
+}
+
+wait_for_apache()
+{
+	if ! apache_is_running; then
+		echo -n "Waiting for Apache... "
+		while ! apache_is_running; do
+			sleep 1
+		done
+		echo "done"
+	fi
+}
+
+apache_pid()
+{
+	if apache_is_running; then
+		cat "$APACHE_PIDFILE"
+	else
+		echo "Unable to get Apache PID as it's not yet running" >&2
+		echo ""
+	fi
+}
+
+apache_http_port()
+{
+	if [ ! -f "$APACHE_HTTP_PORT_FILE" ]; then
+		apache_set_http_port "80"
+	fi
+
+	cat "$APACHE_HTTP_PORT_FILE"
+}
+
+apache_set_http_port()
+{
+	echo "$1" > "$APACHE_HTTP_PORT_FILE"
+}
+
+apache_https_port()
+{
+	if [ ! -f "$APACHE_HTTPS_PORT_FILE" ]; then
+		apache_set_https_port "443"
+	fi
+
+	cat "$APACHE_HTTPS_PORT_FILE"
+}
+
+apache_set_https_port()
+{
+	echo "$1" > "$APACHE_HTTPS_PORT_FILE"
 }
