Improve import-data to handle keys and certs

diff --git a/src/import-export/bin/import-data b/src/import-export/bin/import-data
--- a/src/import-export/bin/import-data
+++ b/src/import-export/bin/import-data
@@ -22,8 +22,9 @@ print_usage()
 	echo "Usage:"
 	echo "    $COMMAND [OPTIONS] <backup dir>"
 	echo "    Import data exported from another Nextcloud snap instance."
-	echo "    By default this imports the database, config, and data"
-	echo "    (equivalent to running $COMMAND -abcd)."
+	echo "    By default this imports the"
+        echo "    apps, database, config, certs, keys, and data"
+	echo "    (equivalent to running $COMMAND -abcdef)."
 	echo ""
 	echo "Available options:"
 	echo "    -h: Display this help message"
@@ -31,6 +32,8 @@ print_usage()
 	echo "    -b: Import the database"
 	echo "    -c: Import the config"
 	echo "    -d: Import the data"
+	echo "    -e: Import the encryption keys"
+	echo "    -f: Import the certificates"
 }
 
 import_apps()
@@ -92,10 +95,51 @@ import_data()
 	fi
 }
 
+import_keys()
+{
+	backup_dir="${1%/}"
+        keys_backup="${backup_dir}/keys"
+	occ_err="/tmp/nextcloud_occ.err"
+	if [ ! -d "$keys_backup" ]; then
+                echo "Encryption keys were not found in the provided backup, skipping."
+	else
+        	run_command "Clearing existing system-wide encryption keys" rm -rf "$NEXTCLOUD_DATA_DIR"/files_encryption
+		run_command "Clearing existing user encryption keys" nextcloud.occ user:list 2>"$occ_err" | awk '{print $3}' | xargs -I{} rm -rf "$NEXTCLOUD_DATA_DIR"/'{}'/files_encryption
+		if [ "$(cat $occ_err)" != "Nextcloud is in maintenance mode - no apps have been loaded" ]; then
+			# ignore the maintenance mode message but print out other errors.
+			echo "WARNING: nextcloud.occ reported an error checking the status of encryption:"
+			cat "$occ_err"
+		fi
+        	echo "Importing encryption keys..."
+        	if ! rsync -ah --info=progress2 "$keys_backup/" "$NEXTCLOUD_DATA_DIR"; then
+                	echo "Unable to import keys"
+                	exit 1
+        	fi
+	fi
+}
+
+import_certs()
+{
+	backup_dir="${1%/}"
+        certs_backup="${backup_dir}/certs"
+	if [ ! -d "$certs_backup" ]; then
+		echo "Certificates were not found in the provided backup, skipping."
+	else
+        	run_command "Clearing existing certificates" rm -rf "$SNAP_DATA/certs"
+        	echo "Importing certificates..."
+        	if ! rsync -ah --info=progress2 "$certs_backup/" "$SNAP_DATA/certs"; then
+                	echo "Unable to import certificates"
+                	exit 1
+        	fi
+	fi
+}
+
 do_import_apps=false
 do_import_database=false
 do_import_config=false
 do_import_data=false
+do_import_keys=false
+do_import_certs=false
 
 # If no parameters are specified, default to importing everything
 if [ $# -eq 1 ]; then
@@ -103,9 +147,11 @@ if [ $# -eq 1 ]; then
 	do_import_database=true
 	do_import_config=true
 	do_import_data=true
+	do_import_keys=false  # keys already get grabbed in a full data import
+	do_import_certs=true
 fi
 
-while getopts ":abcdh" opt; do
+while getopts ":abcdefh" opt; do
 	case $opt in
 		a)
 			do_import_apps=true
@@ -119,6 +165,12 @@ while getopts ":abcdh" opt; do
 		d)
 			do_import_data=true
 			;;
+		e)
+                        do_import_keys=true
+                        ;;
+		f)
+                        do_import_certs=true
+                        ;;
 		h)
 			print_usage
 			exit 0
@@ -162,6 +214,14 @@ fi
 
 if [ "$do_import_config" = true ]; then
 	import_config "$backup_dir"
+fi
+
+if [ "$do_import_keys" = true ] && [ "$do_import_data" = false ]; then
+        import_keys "$backup_dir"
+fi
+
+if [ "$do_import_certs" = true ]; then
+        import_certs "$backup_dir"
 fi
 
 if [ "$do_import_data" = true ]; then
